FROM node:22

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y libreoffice-core libreoffice-writer ghostscript && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY ../app/ ./
RUN npm install
CMD ["node", "index.js"]
